-- Örnek "ortalama" öğrenci verisi — Mert Aydın (iamfurkangul+student3@gmail.com)
-- Neredeyse tüm konularda mütevazı hacimde soru kaydı + tek bir düşük netli TYT denemesi.
-- 0006_student_targets.sql'den SONRA, Supabase SQL Editor'de çalıştırın.
-- Not: bu hesabın profili /kayit üzerinden zaten oluşturulmuş olmalı.

insert into question_logs (student_id, topic_id, log_date, correct_count, wrong_count, blank_count)
select
  (select id from profiles where full_name = 'Mert Aydın' limit 1),
  t.id,
  current_date - d.days_ago,
  d.correct,
  d.wrong,
  d.blank
from (values
  ('Türkçe', 'TYT', 'Sözcükte Anlam', 7, 2, 1, 10),
  ('Türkçe', 'TYT', 'Cümlede Anlam', 5, 6, 0, 3),
  ('Türkçe', 'TYT', 'Paragrafta Anlam', 6, 0, 1, 5),
  ('Türkçe', 'TYT', 'Ses Bilgisi', 2, 4, 0, 11),
  ('Türkçe', 'TYT', 'Yazım Kuralları', 5, 3, 0, 10),
  ('Türkçe', 'TYT', 'Noktalama İşaretleri', 7, 6, 1, 9),
  ('Türkçe', 'TYT', 'Sözcükte Yapı ve Ekler', 2, 2, 0, 3),
  ('Türkçe', 'TYT', 'Sözcük Türleri', 3, 5, 1, 9),
  ('Türkçe', 'TYT', 'Cümlenin Öğeleri', 10, 1, 0, 11),
  ('Türkçe', 'TYT', 'Cümle Türleri', 6, 1, 1, 4),
  ('Türkçe', 'TYT', 'Anlatım Bozuklukları', 2, 2, 0, 13),
  ('Matematik', 'TYT', 'Temel Kavramlar', 4, 2, 0, 8),
  ('Matematik', 'TYT', 'Sayı Basamakları', 7, 5, 0, 3),
  ('Matematik', 'TYT', 'Bölme ve Bölünebilme', 4, 0, 0, 11),
  ('Matematik', 'TYT', 'EBOB-EKOK', 3, 3, 0, 2),
  ('Matematik', 'TYT', 'Rasyonel Sayılar', 5, 2, 0, 5),
  ('Matematik', 'TYT', 'Basit Eşitsizlikler', 4, 3, 0, 10),
  ('Matematik', 'TYT', 'Mutlak Değer', 4, 3, 1, 7),
  ('Matematik', 'TYT', 'Üslü Sayılar', 7, 5, 0, 3),
  ('Matematik', 'TYT', 'Köklü Sayılar', 2, 2, 0, 13),
  ('Matematik', 'TYT', 'Çarpanlara Ayırma', 6, 6, 1, 8),
  ('Matematik', 'TYT', 'Oran Orantı', 2, 7, 1, 9),
  ('Matematik', 'TYT', 'Denklem Çözme', 5, 3, 1, 4),
  ('Matematik', 'TYT', 'Sayı Problemleri', 2, 3, 0, 4),
  ('Matematik', 'TYT', 'Kesir Problemleri', 5, 6, 0, 7),
  ('Matematik', 'TYT', 'Yaş Problemleri', 6, 1, 1, 13),
  ('Matematik', 'TYT', 'İşçi-Havuz Problemleri', 6, 4, 0, 7),
  ('Matematik', 'TYT', 'Hareket Problemleri', 3, 3, 0, 13),
  ('Matematik', 'TYT', 'Yüzde ve Kâr-Zarar Problemleri', 6, 4, 0, 9),
  ('Matematik', 'TYT', 'Karışım Problemleri', 6, 6, 1, 10),
  ('Matematik', 'TYT', 'Kümeler', 7, 3, 1, 2),
  ('Matematik', 'TYT', 'Fonksiyonlar', 2, 2, 0, 3),
  ('Matematik', 'TYT', 'Polinomlar', 6, 6, 0, 4),
  ('Matematik', 'TYT', 'İkinci Dereceden Denklemler', 2, 2, 0, 1),
  ('Matematik', 'TYT', 'Permütasyon ve Kombinasyon', 7, 4, 0, 5),
  ('Matematik', 'TYT', 'Olasılık', 6, 3, 1, 9),
  ('Matematik', 'TYT', 'Veri ve İstatistik', 5, 2, 1, 12),
  ('Geometri', 'TYT', 'Doğruda ve Üçgende Açılar', 2, 5, 1, 7),
  ('Geometri', 'TYT', 'Üçgende Alan ve Benzerlik', 9, 0, 1, 12),
  ('Geometri', 'TYT', 'Özel Üçgenler (Dik, İkizkenar)', 2, 2, 0, 6),
  ('Geometri', 'TYT', 'Çokgenler', 7, 3, 1, 9),
  ('Geometri', 'TYT', 'Dörtgenler', 2, 2, 0, 2),
  ('Geometri', 'TYT', 'Çember ve Daire', 1, 4, 0, 1),
  ('Geometri', 'TYT', 'Analitik Geometri', 2, 3, 0, 0),
  ('Geometri', 'TYT', 'Katı Cisimler', 3, 2, 0, 5),
  ('Fizik', 'TYT', 'Fizik Bilimine Giriş', 7, 3, 1, 9),
  ('Fizik', 'TYT', 'Madde ve Özellikleri', 2, 6, 0, 4),
  ('Fizik', 'TYT', 'Hareket ve Kuvvet', 6, 2, 1, 5),
  ('Fizik', 'TYT', 'Newton''un Hareket Yasaları', 3, 2, 0, 2),
  ('Fizik', 'TYT', 'Enerji ve Enerji Dönüşümleri', 9, 1, 1, 1),
  ('Fizik', 'TYT', 'Isı, Sıcaklık ve Genleşme', 4, 6, 1, 10),
  ('Fizik', 'TYT', 'Elektrostatik', 4, 2, 1, 0),
  ('Fizik', 'TYT', 'Elektrik Akımı ve Devreler', 2, 2, 0, 2),
  ('Fizik', 'TYT', 'Manyetizma', 5, 4, 1, 5),
  ('Fizik', 'TYT', 'Basınç ve Kaldırma Kuvveti', 3, 3, 0, 9),
  ('Fizik', 'TYT', 'Optik (Işık)', 6, 5, 1, 12),
  ('Fizik', 'TYT', 'Dalgalar', 7, 5, 0, 12),
  ('Kimya', 'TYT', 'Kimya Bilimi', 8, 1, 1, 6),
  ('Kimya', 'TYT', 'Atom ve Periyodik Sistem', 9, 5, 0, 8),
  ('Kimya', 'TYT', 'Kimyasal Türler Arası Etkileşimler', 3, 10, 1, 1),
  ('Kimya', 'TYT', 'Maddenin Halleri', 9, 4, 1, 9),
  ('Kimya', 'TYT', 'Kimyanın Temel Kanunları', 5, 4, 1, 8),
  ('Kimya', 'TYT', 'Mol Kavramı', 6, 3, 1, 13),
  ('Kimya', 'TYT', 'Karışımlar', 4, 1, 0, 1),
  ('Kimya', 'TYT', 'Asit, Baz ve Tuz', 7, 6, 0, 4),
  ('Kimya', 'TYT', 'Kimya Her Yerde', 7, 2, 0, 4),
  ('Biyoloji', 'TYT', 'Canlıların Ortak Özellikleri', 4, 4, 0, 3),
  ('Biyoloji', 'TYT', 'Canlıların Temel Bileşenleri', 8, 4, 0, 4),
  ('Biyoloji', 'TYT', 'Hücre ve Organeller', 5, 2, 0, 3),
  ('Biyoloji', 'TYT', 'Canlıların Sınıflandırılması', 8, 4, 2, 8),
  ('Biyoloji', 'TYT', 'Hücre Bölünmeleri (Mitoz-Mayoz)', 6, 2, 0, 9),
  ('Biyoloji', 'TYT', 'Kalıtım', 3, 2, 0, 11),
  ('Biyoloji', 'TYT', 'Ekosistem Ekolojisi', 3, 2, 0, 1),
  ('Tarih', 'TYT', 'Tarih ve Zaman', 9, 4, 1, 4),
  ('Tarih', 'TYT', 'İnsanlığın İlk Dönemleri', 3, 3, 1, 11),
  ('Tarih', 'TYT', 'Ortaçağda Dünya', 2, 2, 0, 10),
  ('Tarih', 'TYT', 'İlk ve Orta Çağlarda Türk Dünyası', 4, 2, 1, 8),
  ('Tarih', 'TYT', 'İslam Tarihi ve Uygarlığı', 11, 1, 2, 2),
  ('Tarih', 'TYT', 'Türk İslam Devletleri', 2, 2, 0, 1),
  ('Tarih', 'TYT', 'Beylikten Devlete Osmanlı', 8, 3, 1, 11),
  ('Tarih', 'TYT', 'Dünya Gücü Osmanlı', 4, 8, 1, 10),
  ('Tarih', 'TYT', 'Yerleşme ve Devletleşme Sürecinde Savaşçılar', 6, 1, 0, 5),
  ('Tarih', 'TYT', 'Değişim Çağı', 3, 1, 0, 9),
  ('Tarih', 'TYT', 'Uluslararası İlişkilerde Denge Stratejisi', 9, 3, 0, 8),
  ('Tarih', 'TYT', 'Devrimler Çağında Değişen Devlet-Toplum İlişkileri', 6, 6, 1, 13),
  ('Coğrafya', 'TYT', 'Doğa ve İnsan', 6, 7, 0, 4),
  ('Coğrafya', 'TYT', 'Dünya''nın Şekli ve Hareketleri', 13, 0, 2, 4),
  ('Coğrafya', 'TYT', 'Coğrafi Konum', 3, 3, 0, 10),
  ('Coğrafya', 'TYT', 'Harita Bilgisi', 6, 6, 2, 11),
  ('Coğrafya', 'TYT', 'İklim Bilgisi', 6, 0, 1, 5),
  ('Coğrafya', 'TYT', 'Yer Şekillerinin Oluşumu (İç Kuvvetler)', 4, 4, 1, 4),
  ('Coğrafya', 'TYT', 'Yer Şekillerinin Oluşumu (Dış Kuvvetler)', 6, 1, 1, 9),
  ('Coğrafya', 'TYT', 'Nüfus', 6, 3, 1, 4),
  ('Coğrafya', 'TYT', 'Yerleşme', 3, 3, 0, 6),
  ('Coğrafya', 'TYT', 'Türkiye''nin Yer Şekilleri', 3, 2, 0, 3),
  ('Coğrafya', 'TYT', 'Ekonomik Faaliyetler', 3, 2, 0, 3),
  ('Felsefe', 'TYT', 'Felsefeye Giriş', 9, 4, 1, 10),
  ('Felsefe', 'TYT', 'Bilgi Felsefesi', 8, 3, 1, 10),
  ('Felsefe', 'TYT', 'Varlık Felsefesi', 6, 3, 1, 10),
  ('Felsefe', 'TYT', 'Ahlak Felsefesi', 7, 6, 0, 3),
  ('Felsefe', 'TYT', 'Din Felsefesi', 4, 1, 0, 7),
  ('Felsefe', 'TYT', 'Siyaset Felsefesi', 2, 2, 0, 11),
  ('Felsefe', 'TYT', 'Sanat Felsefesi', 5, 7, 0, 1),
  ('Din Kültürü ve Ahlak Bilgisi', 'TYT', 'Bilgi ve İnanç', 7, 5, 1, 12),
  ('Din Kültürü ve Ahlak Bilgisi', 'TYT', 'İbadet', 7, 3, 0, 12),
  ('Din Kültürü ve Ahlak Bilgisi', 'TYT', 'Ahlaki Tutum ve Davranışlar', 8, 3, 1, 6),
  ('Din Kültürü ve Ahlak Bilgisi', 'TYT', 'Hz. Muhammed''in Hayatı', 6, 3, 1, 13),
  ('Din Kültürü ve Ahlak Bilgisi', 'TYT', 'Vahiy ve Akıl', 8, 3, 1, 2),
  ('Din Kültürü ve Ahlak Bilgisi', 'TYT', 'Din ve Hayat', 8, 2, 1, 13),
  ('Matematik', 'AYT', 'Fonksiyonlarda İleri Konular', 3, 2, 0, 9),
  ('Matematik', 'AYT', 'Polinomlarda İleri Konular', 3, 1, 0, 13),
  ('Matematik', 'AYT', 'İkinci Dereceden Denklemlerde İleri Konular', 6, 4, 0, 6),
  ('Matematik', 'AYT', 'Trigonometri', 3, 9, 0, 2),
  ('Matematik', 'AYT', 'Logaritma', 8, 4, 1, 7),
  ('Matematik', 'AYT', 'Diziler', 3, 9, 1, 10),
  ('Matematik', 'AYT', 'Limit ve Süreklilik', 7, 4, 1, 8),
  ('Matematik', 'AYT', 'Türev', 7, 4, 1, 6),
  ('Matematik', 'AYT', 'İntegral', 5, 3, 0, 3),
  ('Matematik', 'AYT', 'Analitik Geometride İleri Konular', 3, 3, 0, 1),
  ('Geometri', 'AYT', 'Çokgenlerde İleri Konular', 3, 2, 0, 13),
  ('Geometri', 'AYT', 'Çemberde Analitik Yaklaşım', 2, 2, 0, 5),
  ('Geometri', 'AYT', 'Katı Cisimlerde İleri Konular', 7, 4, 1, 5),
  ('Geometri', 'AYT', 'Vektörler', 5, 3, 1, 7),
  ('Geometri', 'AYT', 'Uzay Geometri', 4, 2, 0, 9),
  ('Fizik', 'AYT', 'Kuvvet ve Hareket (İleri)', 6, 3, 0, 5),
  ('Fizik', 'AYT', 'Elektrik ve Manyetizma (İleri)', 3, 2, 0, 6),
  ('Fizik', 'AYT', 'Optik (İleri)', 3, 3, 0, 11),
  ('Fizik', 'AYT', 'Modern Fizik', 3, 3, 0, 12),
  ('Fizik', 'AYT', 'Çembersel Hareket', 4, 2, 1, 1),
  ('Fizik', 'AYT', 'Basit Harmonik Hareket', 2, 2, 0, 8),
  ('Fizik', 'AYT', 'Dalga Mekaniği (İleri)', 1, 3, 0, 1),
  ('Kimya', 'AYT', 'Kimyasal Tepkimelerde Enerji', 8, 1, 0, 11),
  ('Kimya', 'AYT', 'Kimyasal Tepkime Hızı', 6, 5, 1, 6),
  ('Kimya', 'AYT', 'Kimyasal Denge', 4, 1, 0, 1),
  ('Kimya', 'AYT', 'Asit-Baz Dengesi', 5, 4, 1, 4),
  ('Kimya', 'AYT', 'Çözünürlük Dengesi', 9, 0, 1, 1),
  ('Kimya', 'AYT', 'Elektrokimya', 6, 5, 0, 9),
  ('Kimya', 'AYT', 'Karbon Kimyasına Giriş', 8, 1, 0, 8),
  ('Kimya', 'AYT', 'Organik Kimya', 7, 1, 0, 5),
  ('Biyoloji', 'AYT', 'Sinir Sistemi', 5, 1, 0, 13),
  ('Biyoloji', 'AYT', 'Endokrin Sistem', 7, 2, 0, 13),
  ('Biyoloji', 'AYT', 'Duyu Organları', 3, 3, 0, 6),
  ('Biyoloji', 'AYT', 'Destek ve Hareket Sistemi', 5, 4, 1, 12),
  ('Biyoloji', 'AYT', 'Sindirim Sistemi', 1, 4, 0, 7),
  ('Biyoloji', 'AYT', 'Dolaşım ve Bağışıklık Sistemi', 5, 4, 1, 0),
  ('Biyoloji', 'AYT', 'Solunum Sistemi', 2, 4, 0, 8),
  ('Biyoloji', 'AYT', 'Üriner Sistem', 2, 2, 0, 5),
  ('Biyoloji', 'AYT', 'Üreme Sistemi ve Embriyonik Gelişim', 8, 3, 1, 10),
  ('Biyoloji', 'AYT', 'Komünite ve Popülasyon Ekolojisi', 3, 4, 0, 5),
  ('Biyoloji', 'AYT', 'Genden Proteine', 1, 6, 0, 13),
  ('Biyoloji', 'AYT', 'Canlılarda Enerji Dönüşümleri', 1, 3, 0, 10),
  ('Biyoloji', 'AYT', 'Bitki Biyolojisi', 7, 4, 1, 2),
  ('Edebiyat', 'AYT', 'Anlam Bilgisi', 6, 5, 1, 0),
  ('Edebiyat', 'AYT', 'Şiir Bilgisi', 7, 4, 0, 11),
  ('Edebiyat', 'AYT', 'Edebi Sanatlar', 8, 3, 1, 9),
  ('Edebiyat', 'AYT', 'Anlatım Teknikleri', 5, 3, 1, 8),
  ('Edebiyat', 'AYT', 'Tanzimat ve Servet-i Fünun Dönemi', 6, 5, 1, 4),
  ('Edebiyat', 'AYT', 'Milli Edebiyat Dönemi', 3, 2, 0, 9),
  ('Edebiyat', 'AYT', 'Cumhuriyet Dönemi Türk Edebiyatı', 4, 5, 0, 11),
  ('Edebiyat', 'AYT', 'Dünya Edebiyatı', 4, 1, 0, 9),
  ('Tarih', 'AYT', 'XX. Yüzyıl Başlarında Osmanlı ve Dünya', 2, 5, 1, 0),
  ('Tarih', 'AYT', 'I. Dünya Savaşı', 3, 8, 1, 10),
  ('Tarih', 'AYT', 'Milli Mücadele', 8, 2, 0, 6),
  ('Tarih', 'AYT', 'Atatürk İlkeleri ve İnkılap Tarihi', 8, 3, 1, 13),
  ('Tarih', 'AYT', 'İkinci Dünya Savaşı', 5, 9, 0, 13),
  ('Tarih', 'AYT', 'Soğuk Savaş Dönemi', 7, 7, 0, 10),
  ('Tarih', 'AYT', 'Yumuşama Dönemi ve Sonrası', 8, 2, 0, 2),
  ('Coğrafya', 'AYT', 'Ekosistem', 8, 0, 1, 12),
  ('Coğrafya', 'AYT', 'Nüfus Politikaları', 5, 4, 1, 13),
  ('Coğrafya', 'AYT', 'Şehirler ve Etki Alanları', 9, 3, 1, 9),
  ('Coğrafya', 'AYT', 'Türkiye Ekonomisi', 6, 6, 2, 7),
  ('Coğrafya', 'AYT', 'Bölgeler ve Kalkınma', 3, 2, 0, 9),
  ('Coğrafya', 'AYT', 'Çevre ve Toplum', 4, 3, 1, 8),
  ('Coğrafya', 'AYT', 'Küresel Ortam: Bölgeler ve Ülkeler', 3, 3, 0, 4)
) as d(subject_name, exam_type, topic_name, correct, wrong, blank, days_ago)
join subjects s on s.name = d.subject_name and s.exam_type = d.exam_type::exam_type
join topics t on t.subject_id = s.id and t.name = d.topic_name;

values (
  (select id from profiles where full_name = 'Mert Aydın' limit 1),
  'Karekök Yayınları TYT Deneme 3',
  'TYT',
  current_date - 2,
  '[
    {"subject_name":"Türkçe","correct":6,"wrong":6,"net":4.5},
    {"subject_name":"Matematik","correct":4,"wrong":8,"net":2},
    {"subject_name":"Geometri","correct":3,"wrong":4,"net":2},
    {"subject_name":"Fizik","correct":2,"wrong":4,"net":1},
    {"subject_name":"Kimya","correct":3,"wrong":4,"net":2},
    {"subject_name":"Biyoloji","correct":3,"wrong":2,"net":2.5},
    {"subject_name":"Tarih","correct":2,"wrong":2,"net":1.5},
    {"subject_name":"Coğrafya","correct":2,"wrong":4,"net":1},
    {"subject_name":"Felsefe","correct":2,"wrong":4,"net":1},
    {"subject_name":"Din Kültürü ve Ahlak Bilgisi","correct":2,"wrong":4,"net":1}
  ]'::jsonb,
  18.5
);
